GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/63b3906f4dfaa8487b7e472a

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "east",
  "subscribedToChannel": "Dev App"
}

###
DELETE http://localhost:3000/subscribers/63b395f6b6c706f7dfe026ab

###
PATCH http://localhost:3000/subscribers/63b3906f4dfaa8487b7e472a
Content-Type: application/json

{
  "name": "patch!!!! east",
  "subscribedToChannel": "patch Dev App"
}